version: '3.8'

networks:
  1panel-network:
    external: true

services:
  aris-blog-web:
    image: ghcr.io/hcd233/aris-blog-web:master # aris-mem-api:latest
    container_name: aris-blog-web
    restart: always
    networks:
      - 1panel-network
    ports:
      - "6000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
